apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPNAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: APPNAME_PLACEHOLDER
    spec:
      containers:
        - name: APPNAME_PLACEHOLDER
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: APPNAME_PLACEHOLDER
spec:
  type: LoadBalancer
  selector:
    app: APPNAME_PLACEHOLDER
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
